<?php

namespace GGGGino\SkuskuCartBundle\Repository;

/**
 * CartRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CartRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Prendo tutti i carrelli attivi non eliminati
     */
    public function getNonOrderedCart()
    {

    }
}
