<?php

namespace GGGGino\SkuskuCartBundle\Repository;

/**
 * GenderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerRepository extends \Doctrine\ORM\EntityRepository
{
}
